experiment_type: "linear_annealing"

common:
  n_steps: 200000
  n_runs: 5
  verbose: true
  initialization: klarner

constant_beta:
  N: 5
  beta_const: 1.0
  base_seed: 42
  output_path: "figures/energy_history_metropolis.png"

linear_annealing:
  N: 13
  beta_start: 0.1
  beta_end: 10.0
  base_seed: 123
  output_path: "figures/energy_history_la.png"

exponential_annealing:
  N: 5
  beta_start: 0.1
  beta_end: 5.0
  base_seed: 123
  output_path: "figures/energy_history_ea.png"

measure_min_energy_vs_N:
  Ns: [3, 4, 5, 6, 7, 8]
  n_steps: 100000
  beta_schedule_type: "constant_beta"
  beta_const: 1.0
  beta_start: 0.1
  beta_end: 5.0
  base_seed: 500
  output_path: "figures/min_energy_vs_N.png"
