experiment_type: "single_N"

common:
  n_steps: 10000
  n_runs: 30
  verbose: true
  initialization: random

  betta_scheduling:
    type: ["linear_annealing", "exponential_annealing", "constant"]
    base_seed: 42
    beta_const: 3.0
    beta_start: 1
    beta_end: 10.0

  output_path: "figures/energy_history_singleN.png"
single_N:
  N: 15

measure_min_energy_vs_N:
  Ns: [3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
  init_modes: ["random", "klarner","latin"]