experiment_type: "measure_min_energy_vs_N""

common:
  n_steps: 1000000
  n_runs: 20
  verbose: true
  initialization: random

  betta_scheduling:
    type: "linear_annealing"
    base_seed: 42
    beta_const: 3.0
    beta_start: 1
    beta_end: 10.0

  output_path: "figures/multiple_N_Miquel.png"
single_N:
  N: 15

measure_min_energy_vs_N:
  Ns: [3,5,7,9,11,13,15,17,19]
  init_modes: ["random", "klarner","latin"]