experiment_type: "single_N"

common:
  n_steps: 200000
  n_runs: 13
  verbose: true
  initialization: klarner

  # Global beta scheduling config
  betta_scheduling:
    type: "linear_annealing"          # or "linear_annealing", "exponential_annealing"
    base_seed: 42             # default base seed for this experiment
    beta_const: 1.0           # used if type == "constant"
    beta_start: 0.1           # used if type != "constant"
    beta_end: 10.0            # used if type != "constant"

  output_path: "figures/energy_history_singleN.png"

# Per-experiment params for single_N
single_N:
  N: 13

# You can keep this block as-is if you still want the other experiment type:
measure_min_energy_vs_N:
  Ns: [3, 4, 5, 6, 7, 8]
